# Generated by Django 2.1.9 on 2020-01-04 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=325)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=10)),
                ('info', models.TextField(null='true')),
                ('remise', models.PositiveIntegerField(default=0)),
                ('livraison', models.PositiveIntegerField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('produit', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('prix', models.PositiveIntegerField()),
                ('user', models.CharField(max_length=255)),
                ('commission', models.PositiveIntegerField()),
                ('qtt', models.PositiveIntegerField()),
                ('Commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandes.Commande')),
            ],
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=55)),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='etat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commandes.Etat'),
        ),
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Wilaya'),
        ),
    ]
