# Generated by Django 2.1.9 on 2020-01-07 06:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_userprofile_commune'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePayement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank='True', default=datetime.datetime.now)),
                ('montant', models.PositiveIntegerField()),
                ('methode', models.CharField(choices=[('Virement ccp', 'Virement ccp'), ('Virement Bancaire', 'Virement Bancaire'), ('Cash', 'Cash')], max_length=255)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
