# Generated by Django 2.1.9 on 2020-01-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_demandepayement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepayement',
            name='message',
            field=models.TextField(blank='True', null='True'),
        ),
    ]
