# Generated by Django 2.1.9 on 2020-01-04 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique='True')),
                ('image', models.ImageField(blank='True', null='True', upload_to='categories')),
                ('commission', models.PositiveIntegerField(default=5)),
                ('parent', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='categories.Categorie')),
            ],
        ),
    ]
