# Generated by Django 2.1.9 on 2020-01-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='code',
        ),
    ]
