# Generated by Django 2.1.9 on 2020-01-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='etat',
            field=models.CharField(choices=[('neuf', 'neuf'), ('ocasion', 'ocasion')], default='neuf', max_length=255),
        ),
    ]
